openapi: 3.0.1
info:
  title: kotohiro
  description: ''
  version: 1.0.0
tags:
  - name: vote
  - name: opinion
  - name: talk_session
  - name: user
  - name: auth
paths:
  /talksessions/{talkSessionID}/opinions/{opinionID}/votes:
    post:
      summary: ÊÑèÊÄùË°®ÊòéAPI
      deprecated: false
      description: ''
      operationId: vote
      tags:
        - vote
      parameters:
        - name: talkSessionID
          in: path
          description: „Çª„ÉÉ„Ç∑„Éß„É≥„ÅÆID
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: ÊÑèË¶ã„ÅÆID
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                voteStatus:
                  type: string
                  enum:
                    - agree
                    - disagree
                    - pass
                  example: ''
                  nullable: true
              required:
                - voteStatus
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items: &ref_0
                  $ref: '#/components/schemas/opinion'
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Vote
  /talksession/{talkSessionID}/swipe_opinions:
    get:
      summary: „Çπ„ÉØ„Ç§„ÉóÁî®„ÅÆ„Ç®„É≥„Éâ„Éù„Ç§„É≥„Éà
      deprecated: false
      description: „Çª„ÉÉ„Ç∑„Éß„É≥„ÅÆ‰∏≠„Åã„Çâ„Åæ„Å†ÊäïÁ•®„Åó„Å¶„ÅÑ„Å™„ÅÑÊÑèË¶ã„Çí„É©„É≥„ÉÄ„É†„Å´ÂèñÂæó„Åô„Çã
      operationId: swipe_opinions
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    opinion: *ref_0
                    user: &ref_1
                      $ref: '#/components/schemas/user'
                      description: ‰ΩúÊàê„É¶„Éº„Ç∂„Éº
                    replyCount:
                      type: integer
                  required:
                    - opinion
                    - user
                    - replyCount
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionId}/opinion:
    get:
      summary: üöß ÂàÜÊûê„Å´Èñ¢„Åô„ÇãÊÑèË¶ã
      deprecated: false
      description: ''
      operationId: getTopOpinions
      tags:
        - opinion
      parameters:
        - name: talkSessionId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
                required:
                  - 01J93WTW4J3ZBAAVVZV8PSWZ6R
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionID}/opinions:
    post:
      summary: „Çª„ÉÉ„Ç∑„Éß„É≥„Å´ÂØæ„Åó„Å¶ÊÑèË¶ãÊäïÁ®ø
      deprecated: false
      description: parentOpinionID„Åå„Å™„Åë„Çå„Å∞„É´„Éº„Éà„ÅÆÊÑèË¶ã„Å®„Åó„Å¶ÊäïÁ®ø„Åï„Çå„Çã
      operationId: postOpinionPost
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                parentOpinionID:
                  type: string
                  example: ''
                  nullable: true
                title:
                  type: string
                  example: ''
                  nullable: true
                opinionContent:
                  type: string
                  maxLength: 140
                  example: ''
                referenceURL:
                  type: string
                  format: url
                  example: ''
                  nullable: true
                picture:
                  type: string
                  format: binary
                  description: ÂèÇËÄÉÁîªÂÉè„ÄÇ4MiB„Åæ„Åß
                  example: ''
              required:
                - opinionContent
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionID}/opinions/{opinionID}/replies:
    get:
      summary: ÊÑèË¶ã„Å´ÂØæ„Åô„Çã„Ç≥„É°„É≥„Éà‰∏ÄË¶ß„ÇíËøî„Åô
      deprecated: false
      description: ''
      operationId: opinionComments
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: Ë¶™ÊÑèË¶ã„ÅÆID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  rootOpinion:
                    type: object
                    properties:
                      user: *ref_1
                      opinion: *ref_0
                    required:
                      - user
                      - opinion
                  myVoteType:
                    anyOf:
                      - &ref_2
                        $ref: '#/components/schemas/voteType'
                        description: ÊÑèË¶ãÊäïÁ®ø‰∏ª„ÅÆÊÑèË¶ã„ÄÇ„É´„Éº„ÉàÊÑèË¶ã„ÅÆÂ†¥Âêà„ÅØ„Åì„Åì„Å´„ÅØ‰Ωï„ÇÇÂÖ•„Çâ„Å™„ÅÑ
                      - type: 'null'
                  opinions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinion: *ref_0
                        user: *ref_1
                        myVoteType:
                          anyOf:
                            - *ref_2
                            - type: 'null'
                      required:
                        - opinion
                        - user
                required:
                  - rootOpinion
                  - opinions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionId}:
    get:
      summary: üöß „Éà„Éº„ÇØ„Çª„ÉÉ„Ç∑„Éß„É≥„ÅÆË©≥Á¥∞
      deprecated: false
      description: ''
      operationId: getTalkSessionDetail
      tags:
        - talk_session
      parameters:
        - name: talkSessionId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: &ref_3
                $ref: '#/components/schemas/talkSession'
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
  /talksessions:
    get:
      summary: „Éà„Éº„ÇØ„Çª„ÉÉ„Ç∑„Éß„É≥„Ç≥„É¨„ÇØ„Ç∑„Éß„É≥
      deprecated: false
      description: ''
      operationId: getTalkSessionList
      tags:
        - talk_session
      parameters:
        - name: limit
          in: query
          description: 1„Éö„Éº„Ç∏„ÅÇ„Åü„Çä„ÅÆË¶ÅÁ¥†Êï∞
          required: false
          example: 10
          schema:
            type: integer
            nullable: true
        - name: offset
          in: query
          description: „Å©„ÅÆË¶ÅÁ¥†„Åã„ÇâÂßã„ÇÅ„Çã„Åã
          required: false
          example: 0
          schema:
            type: integer
            nullable: true
        - name: theme
          in: query
          description: ''
          required: false
          schema:
            type: string
            nullable: true
        - name: status
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - open
              - finished
            default: open
            x-apidog-enum:
              - name: ''
                value: open
                description: ÈñãÂÇ¨‰∏≠
              - name: ''
                value: finished
                description: ÁµÇ‰∫ÜÊ∏à„Åø
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  talkSessions:
                    type: array
                    items:
                      type: object
                      properties:
                        talkSession: *ref_3
                        opinionCount:
                          type: integer
                      required:
                        - talkSession
                        - opinionCount
                  pagination:
                    $ref: '#/components/schemas/offsetPagination'
                required:
                  - talkSessions
                  - pagination
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
    post:
      summary: „Éà„Éº„ÇØ„Çª„ÉÉ„Ç∑„Éß„É≥‰ΩúÊàê
      deprecated: false
      description: ''
      operationId: createTalkSession
      tags:
        - talk_session
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                theme:
                  type: string
                  maxLength: 50
                  minLength: 5
                  example: „Ç™„Éñ„Ç∏„Çß„ÇØ„ÉàÊåáÂêë„ÅØÊÇ™
                scheduledEndTime:
                  type: string
                  format: date-time
                  example: '2024-12-17T03:24:00Z'
                latitude:
                  type: number
                  description: Á∑ØÂ∫¶
                  example: 0
                  nullable: true
                longitude:
                  type: number
                  description: ÁµåÂ∫¶
                  example: 0
                  nullable: true
                city:
                  type: string
                  description: Â∏ÇÂå∫Áî∫Êùë
                  example: ''
                  nullable: true
                prefecture:
                  type: string
                  description: ÈÉΩÈÅìÂ∫úÁúå
                  example: ''
                  nullable: true
              required:
                - theme
                - scheduledEndTime
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: „Éà„Éº„ÇØ„Çª„ÉÉ„Ç∑„Éß„É≥ID
                  theme:
                    type: string
                    description: „ÉÜ„Éº„Éû
                  owner: *ref_1
                  createdAt:
                    type: string
                    description: ‰ΩúÊàêÊó•ÊôÇ
                  scheduledEndTime:
                    type: string
                    description: ÁµÇ‰∫Ü‰∫àÂÆöÊó•ÊôÇ
                  location:
                    anyOf:
                      - &ref_4
                        $ref: '#/components/schemas/location'
                      - type: 'null'
                    description: ‰ΩçÁΩÆÊÉÖÂ†±
                  city:
                    type: string
                    description: Â∏ÇÂå∫Áî∫Êùë
                    nullable: true
                  prefecture:
                    type: string
                    description: ÈÉΩÈÅìÂ∫úÁúå
                    nullable: true
                required:
                  - id
                  - theme
                  - owner
                  - createdAt
                  - scheduledEndTime
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: TalkSession
  /user:
    put:
      summary: „É¶„Éº„Ç∂„ÉºÊÉÖÂ†±„ÅÆÂ§âÊõ¥
      deprecated: false
      description: ''
      operationId: editUserProfile
      tags:
        - user
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  description: „É¶„Éº„Ç∂„ÉºÂêç
                  example: ''
                  nullable: true
                icon:
                  type: string
                  format: binary
                  description: „É¶„Éº„Ç∂„Éº„Ç¢„Ç§„Ç≥„É≥
                  example: ''
                yearOfBirth:
                  type: integer
                  description: Áîü„Åæ„ÇåÂπ¥
                  example: 0
                  nullable: true
                gender:
                  type: string
                  enum:
                    - Áî∑ÊÄß
                    - Â•≥ÊÄß
                    - „Åù„ÅÆ‰ªñ
                    - ÂõûÁ≠î„Åó„Å™„ÅÑ
                  description: ÊÄßÂà•
                  example: ''
                  nullable: true
                city:
                  type: string
                  description: Â∏ÇÂå∫Áî∫Êùë
                  example: ''
                  nullable: true
                occupation:
                  type: string
                  enum:
                    - Ê≠£Á§æÂì°
                    - Â•ëÁ¥ÑÁ§æÂì°
                    - ÂÖ¨ÂãôÂì°
                    - Ëá™Âñ∂Ê•≠
                    - ‰ºöÁ§æÂΩπÂì°
                    - „Éë„Éº„Éà„Éª„Ç¢„É´„Éê„Ç§„Éà
                    - ÂÆ∂‰∫ãÂæì‰∫ãËÄÖ
                    - Â≠¶Áîü
                    - ÁÑ°ËÅ∑
                    - „Åù„ÅÆ‰ªñ
                    - ÂõûÁ≠î„Åó„Å™„ÅÑ
                  description: ËÅ∑Ê•≠
                  example: ''
                  nullable: true
                householdSize:
                  type: integer
                  description: ‰∏ñÂ∏Ø‰∫∫Êï∞
                  example: 0
                  nullable: true
                prefectures:
                  type: string
                  description: ÈÉΩÈÅìÂ∫úÁúå
                  example: ''
                  nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  displayID:
                    type: string
                    pattern: ^[A-Za-z0-9]$
                    examples:
                      - userid
                    minLength: 3
                    maxLength: 25
                  displayName:
                    type: string
                  iconURL:
                    type: string
                    nullable: true
                required:
                  - displayID
                  - displayName
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: user
    get:
      summary: „É¶„Éº„Ç∂„ÉºÊÉÖÂ†±„ÅÆÂèñÂæó
      deprecated: false
      description: ''
      operationId: get_user_info
      tags:
        - user
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  user: *ref_1
                  demographics:
                    $ref: '#/components/schemas/userDemographics'
                required:
                  - user
                  - demographics
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: User
    post:
      summary: „É¶„Éº„Ç∂„Éº‰ΩúÊàê
      deprecated: false
      description: ''
      operationId: registerUser
      tags:
        - user
      parameters:
        - name: SessionId
          in: cookie
          description: ''
          required: false
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJrb3RvaGlyby5jb20iLCJkaXNwbGF5SWQiOm51bGwsImRpc3BsYXlOYW1lIjpudWxsLCJleHAiOjE3Mjg4OTM0NzAsImlhdCI6MTcyODgwNzA3MCwiaWNvblVSTCI6bnVsbCwiaXNWZXJpZnkiOmZhbHNlLCJpc3MiOiJrb3RvaGlyby5jb20iLCJqdGkiOiIwMTkyODRlZS02OWQwLTc3MWUtOTZjZi0xMDcyMjdmNDM2ODYiLCJzdWIiOiIwMTkyODRlYy01YzJhLTc1MzUtOTg2Yi03NTU3NWVhZTg3MjgifQ.APv33CyxLOlu4cuukgdqLEIsUq0CM7dMg66A6tutyuw
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  description: „É¶„Éº„Ç∂„ÉºÂêç„ÄÇÊó•Êú¨Ë™û„Å™„Å©„ÇÇË®≠ÂÆöÂèØËÉΩ„ÄÇ
                  example: hogesge
                displayID:
                  type: string
                  description: „É¶„Éº„Ç∂„ÉºID„ÄÇ„Éó„É≠„Éï„Ç£„Éº„É´„ÅÆ„Éë„Çπ„Å™„Å©„Åß‰ΩøÁî®„Åï„Çå„Çã„ÄÇDB„ÅÆID„Å®„ÅØÂà•„ÄÇ
                  example: suge-
                icon:
                  format: binary
                  type: string
                  description: „É¶„Éº„Ç∂„Éº„Ç¢„Ç§„Ç≥„É≥
                  example: ''
                yearOfBirth:
                  type: integer
                  default: 0
                  description: Áîü„Åæ„ÇåÂπ¥
                  example: 0
                  nullable: true
                gender:
                  type: string
                  enum:
                    - Áî∑ÊÄß
                    - Â•≥ÊÄß
                    - „Åù„ÅÆ‰ªñ
                    - ÂõûÁ≠î„Åó„Å™„ÅÑ
                  default: preferNotToSay
                  description: ÊÄßÂà•
                  example: ''
                  nullable: true
                prefectures:
                  description: ÈÉΩÈÅìÂ∫úÁúå
                  example: ''
                  type: string
                city:
                  type: string
                  description: Â∏ÇÂå∫Áî∫Êùë
                  example: ''
                  nullable: true
                occupation:
                  type: string
                  enum:
                    - Ê≠£Á§æÂì°
                    - Â•ëÁ¥ÑÁ§æÂì°
                    - ÂÖ¨ÂãôÂì°
                    - Ëá™Âñ∂Ê•≠
                    - ‰ºöÁ§æÂΩπÂì°
                    - „Éë„Éº„Éà„Éª„Ç¢„É´„Éê„Ç§„Éà
                    - ÂÆ∂‰∫ãÂæì‰∫ãËÄÖ
                    - Â≠¶Áîü
                    - ÁÑ°ËÅ∑
                    - „Åù„ÅÆ‰ªñ
                    - ÂõûÁ≠î„Åó„Å™„ÅÑ
                  default: ÁÑ°ÂõûÁ≠î
                  description: „É¶„Éº„Ç∂„Éº„ÅÆËÅ∑Ê•≠
                  example: ''
                  nullable: true
                householdSize:
                  type: integer
                  minimum: 0
                  description: ‰∏ñÂ∏Ø‰∫∫Êï∞
                  example: 0
                  nullable: true
              required:
                - displayName
                - displayID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  displayID:
                    type: string
                    pattern: ^[A-Za-z0-9]$
                    examples:
                      - userid
                    minLength: 3
                    maxLength: 25
                  displayName:
                    type: string
                  iconURL:
                    type: string
                    nullable: true
                required:
                  - displayID
                  - displayName
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: user
  /opinions/histories:
    get:
      summary: ‰ªä„Åæ„Åß„Å´ÊäïÁ®ø„Åó„ÅüÁï∞Ë¶ã
      deprecated: false
      description: ''
      operationId: opinionsHistory
      tags:
        - user
      parameters:
        - name: sort
          in: query
          description: „ÇΩ„Éº„Éà„Åç„Éº
          required: false
          schema:
            type: string
            enum:
              - latest
              - mostReply
              - oldest
            x-apidog:
              enumDescriptions:
                latest: ÊúÄÊñ∞
                mostReply: „ÇÇ„Å£„Å®„ÇÇ„É™„Éó„É©„Ç§„Åï„Çå„Åü
                oldest: ÊúÄÂè§
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  opinions:
                    type: array
                    items:
                      type: object
                      properties:
                        user: *ref_1
                        opinion: *ref_0
                        replyCount:
                          type: integer
                      required:
                        - user
                        - opinion
                        - replyCount
                required:
                  - opinions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: User
  /sessions/histories:
    get:
      summary: „É™„Ç¢„ÇØ„Ç∑„Éß„É≥Ê∏à„Åø„ÅÆ„Çª„ÉÉ„Ç∑„Éß„É≥‰∏ÄË¶ß
      deprecated: false
      description: ''
      operationId: sessionsHistory
      tags:
        - user
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: User
  /auth/token/info:
    get:
      summary: JWT„ÅÆÂÜÖÂÆπ„ÇíËøî„Åó„Å¶„Åè„Çå„Çã
      deprecated: false
      description: ''
      operationId: oauth_token_info
      tags:
        - auth
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  aud:
                    type: string
                    description: Audience
                  exp:
                    type: string
                    description: ÊúâÂäπÊúüÈôê
                  iat:
                    type: string
                    description: Áô∫Ë°åÊó•ÊôÇ
                  iss:
                    type: string
                    description: Áô∫Ë°åËÄÖ
                  sub:
                    type: string
                    description: „É¶„Éº„Ç∂ID
                  jti:
                    type: string
                    description: JWT ID
                  displayId:
                    type: string
                    description: „É¶„Éº„Ç∂„ÉºID
                  displayName:
                    type: string
                    description: „É¶„Éº„Ç∂„ÉºÂêç
                  iconURL:
                    type: string
                    description: „Ç¢„Ç§„Ç≥„É≥URL
                  isVerify:
                    type: boolean
                    description: „É¶„Éº„Ç∂ÁôªÈå≤Ê∏à„Åø„Åã
                required:
                  - aud
                  - exp
                  - iat
                  - iss
                  - sub
                  - jti
                  - isVerify
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Auth
  /test:
    get:
      summary: OpenAPI„ÉÜ„Çπ„ÉàÁî®
      deprecated: false
      description: ''
      operationId: test
      tags:
        - user
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  optInt:
                    type: integer
                    nullable: true
                  optNilInt:
                    type: integer
                  optNilBool:
                    type: boolean
                    nullable: true
                  optBool:
                    type: boolean
                  optUrl:
                    type: string
                    format: uri
                  optNilUrl:
                    type: string
                    format: url
                    nullable: true
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: test
components:
  schemas:
    talkSession:
      type: object
      properties:
        id:
          type: string
          description: „Éà„Éº„ÇØ„Çª„ÉÉ„Ç∑„Éß„É≥ID
        theme:
          type: string
          description: „ÉÜ„Éº„Éû
        owner: *ref_1
        createdAt:
          type: string
          description: ‰ΩúÊàêÊó•ÊôÇ
        scheduledEndTime:
          type: string
          description: ÁµÇ‰∫Ü‰∫àÂÆöÊó•ÊôÇ
        location:
          anyOf:
            - *ref_4
            - type: 'null'
          description: ‰ΩçÁΩÆÊÉÖÂ†±
        city:
          type: string
          description: Â∏ÇÂå∫Áî∫Êùë
          nullable: true
        prefecture:
          type: string
          description: ÈÉΩÈÅìÂ∫úÁúå
          nullable: true
      required:
        - id
        - theme
        - owner
        - createdAt
        - scheduledEndTime
    validationErrorItem:
      type: object
      properties:
        field:
          type: string
          faker: id
          description: „Éê„É™„Éá„Éº„Ç∑„Éß„É≥„Ç®„É©„Éº„ÅÆ„Éï„Ç£„Éº„É´„Éâ
        message:
          type: string
          description: „Éê„É™„Éá„Éº„Ç∑„Éß„É≥„Ç®„É©„Éº„É°„ÉÉ„Çª„Éº„Ç∏
      required:
        - field
        - message
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    user:
      type: object
      properties:
        displayID:
          type: string
          pattern: ^[A-Za-z0-9]$
          examples:
            - userid
          minLength: 3
          maxLength: 25
        displayName:
          type: string
        iconURL:
          type: string
          nullable: true
      required:
        - displayID
        - displayName
    opinion:
      type: object
      properties:
        id:
          type: string
          faker: '1'
          description: ÊÑèË¶ãID
        title:
          type: string
        content:
          type: string
          description: ÊÑèË¶ã„ÅÆ„ÉÜ„Ç≠„Çπ„Éà
          minLength: 1
          maxLength: 140
        parentID:
          type: string
          description: Ë¶™„ÅÆÊÑèË¶ãID„ÄÇ„É´„Éº„Éà„Å™„Çâ„Å∞ÁÑ°„Åó
        voteType: *ref_2
        pictureURL:
          type: string
          description: ÁîªÂÉè„ÅåËøî„ÇãÂ†¥Âêà„ÇÇ„ÅÇ„Çã
        referenceURL:
          type: string
          description: ÂèÇËÄÉÊñáÁåÆURL
      required:
        - content
        - id
    voteType:
      type: string
      description: ÊÑèË¶ã„ÅÆ3Á®Æ„ÅÆ„Çπ„ÉÜ„Éº„Çø„Çπ
      enum:
        - agree
        - disagree
        - pass
    location:
      type: object
      properties:
        latitude:
          type: number
          description: Á∑ØÂ∫¶
        longitude:
          type: number
          description: ÁµåÂ∫¶
      required:
        - latitude
        - longitude
    tokenClaim:
      type: object
      properties:
        aud:
          type: string
          description: Audience
        exp:
          type: string
          description: ÊúâÂäπÊúüÈôê
        iat:
          type: string
          description: Áô∫Ë°åÊó•ÊôÇ
        iss:
          type: string
          description: Áô∫Ë°åËÄÖ
        sub:
          type: string
          description: „É¶„Éº„Ç∂ID
        jti:
          type: string
          description: JWT ID
        displayId:
          type: string
          description: „É¶„Éº„Ç∂„ÉºID
        displayName:
          type: string
          description: „É¶„Éº„Ç∂„ÉºÂêç
        iconURL:
          type: string
          description: „Ç¢„Ç§„Ç≥„É≥URL
        isVerify:
          type: boolean
          description: „É¶„Éº„Ç∂ÁôªÈå≤Ê∏à„Åø„Åã
      required:
        - aud
        - exp
        - iat
        - iss
        - sub
        - jti
        - isVerify
    offsetPagination:
      type: object
      properties:
        totalCount:
          type: integer
        offset:
          type: integer
        limit:
          type: integer
      required:
        - totalCount
        - offset
        - limit
    userDemographics:
      type: object
      properties:
        yearOfBirth:
          type: integer
          description: Ë™ïÁîüÂπ¥
          nullable: true
        occupation:
          type: string
          title: ËÅ∑Ê•≠
          description: ËÅ∑Ê•≠
        gender:
          type: string
          title: ÊÄßÂà•
          description: ÊÄßÂà•
        city:
          type: string
          title: Â∏ÇÂå∫Áî∫Êùë
          description: Â∏ÇÂå∫Áî∫Êùë
          nullable: true
        householdSize:
          type: integer
          minimum: 1
          maximum: 5
          title: ‰∏ñÂ∏Ø‰∫∫Êï∞
          description: ‰∏ñÂ∏Ø‰∫∫Êï∞
          nullable: true
        prefecture:
          type: string
          description: ÈÉΩÈÅìÂ∫úÁúå
          nullable: true
      required:
        - occupation
        - gender
  securitySchemes:
    apikey-header-SessionId:
      type: apiKey
      in: header
      name: SessionId
servers: []
